Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -9,7 +9,7 @@ trigger:
 stages:
 - stage: build
   jobs:
-  - job: run_build
+  - job: "run_build_push_acr"
     pool:
       vmImage: 'Ubuntu 16.04'
     variables:
@@ -50,11 +50,97 @@ stages:
 - stage: test
   dependsOn: build
   jobs:
-  - job: run_tests
+  - job: update_image_tag
     pool:
       vmImage: 'Ubuntu 16.04'
     steps:
-    - script: echo Test
+    - script: |
+        function get_fab_version() {
+            if [ -z "$VERSION" ]
+            then
+                VERSIONS=$(curl -s https://api.github.com/repos/Microsoft/fabrikate/tags)
+                LATEST_RELEASE=$(echo $VERSIONS | grep "name" | head -1)
+                VERSION_TO_DOWNLOAD=`echo "$LATEST_RELEASE" | cut -d'"' -f 4`
+            else
+                echo "Fabrikate Version: $VERSION"
+                VERSION_TO_DOWNLOAD=$VERSION
+            fi
+        }
+
+        # Obtain OS to download the appropriate version of Fabrikate
+        function get_os() {
+            if [[ "$OSTYPE" == "linux-gnu" ]]; then
+                eval "$1='linux'"
+            elif [[ "$OSTYPE" == "darwin"* ]]; then
+                eval "$1='darwin'"
+            elif [[ "$OSTYPE" == "msys" ]]; then
+                eval "$1='windows'"
+            else
+                eval "$1='linux'"
+            fi
+        }    
+
+        # Download Fabrikate
+        function download_fab() {
+            echo "DOWNLOADING FABRIKATE"
+            echo "Latest Fabrikate Version: $VERSION_TO_DOWNLOAD"
+            os=''
+            get_os os
+            fab_wget=$(wget -SO- "https://github.com/Microsoft/fabrikate/releases/download/$VERSION_TO_DOWNLOAD/fab-v$VERSION_TO_DOWNLOAD-$os-amd64.zip" 2>&1 | egrep -i "302")
+            if [[ $fab_wget == *"302 Found"* ]]; then
+              echo "Fabrikate $VERSION_TO_DOWNLOAD downloaded successfully."
+            else
+                echo "There was an error when downloading Fabrikate. Please check version number and try again."
+            fi
+            wget "https://github.com/Microsoft/fabrikate/releases/download/$VERSION_TO_DOWNLOAD/fab-v$VERSION_TO_DOWNLOAD-$os-amd64.zip"
+            unzip fab-v$VERSION_TO_DOWNLOAD-$os-amd64.zip -d fab
+        }
+
+        # Install Fabrikate
+        function install_fab() {
+            # Run this command to make script exit on any failure
+            set -e
+            export PATH=$PATH:$HOME/fab
+            fab install
+            echo "FAB INSTALL COMPLETED"
+        }
+
+
+        echo "RUN HELM INIT"
+        helm init
+        get_fab_version
+        download_fab
+        ls -la
+        #install_fab
+      displayName: 'Download Fabrikate'
+
+    - script: |
+        function git_connect() {
+        pwd
+            git clone https://automated:b69f2243a8cdf4c6b59fe2c46f7e67bb14e935cd@github.com/andrebriggs/fabrikate-spartan-cluster.git
+
+            cd fabrikate-spartan-cluster
+        }
+        pwd
+        git_connect
+        ../fab/fab set --subcomponent spartan-service image.tag=$(Build.BuildId)
+
+        echo "GIT STATUS"
+        git status
+        echo "GIT ADD (git add -A)"
+        git add -A
+
+        #Set git identity 
+        git config user.email "admin@azuredevops.com"
+        git config user.name "Automated Account"
+
+        echo "GIT COMMIT"
+        git commit -m "Updating image tag to $(Build.BuildId) for common environment"
+
+        echo "GIT PUSH"
+        git push https://b69f2243a8cdf4c6b59fe2c46f7e67bb14e935cd@github.com/andrebriggs/fabrikate-spartan-cluster.git
+
+
     
 # - stage: staging
 #   dependsOn: test
